BLACKLIST = [
    'NPR Music Tiny Desk Concert',
    'NPR',
    'Tiny Desk',
    'Official',
    '(Official Audio)',
    '- Live',
    'www.candyrat.com',
    '( Audio)',
    '(Video Version)',
    '(Lyrics)',
    '( Video)',
    '.wmv',
    'FULL ALBUM',
    'Full Album',
    'YouTube',
    '()',
    '( )',
    '(  )'
]
